# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\OpenApi\JwtDecorator:
        decorates: 'api_platform.openapi.factory'
        arguments: [ '@.inner' ]

    miniblog.events.exception_subscriber:
        class: App\Events\ExceptionSubscriber
        arguments:
            - '@serializer'
        tags:
            - { name: kernel.event_subscriber }


    miniblog.normalizer.resource_access_exception:
        class: App\Normalizer\ResourceAccessExceptionNormalizer
        arguments:
            - { type: 'App\Exceptions\ResourceAccessException' }
        tags:
            - { name: 'miniblog.normalizer' }

    miniblog.normalizer.authentication_exception:
        class: App\Normalizer\AuthenticationExceptionNormalizer
        arguments:
            - { type: 'App\Exceptions\AuthenticationException' }
        tags:
            - { name: 'miniblog.normalizer' }

    miniblog.normalizer.authentication_not_found_exception:
        class: App\Normalizer\NotFoundExceptionNormalizer
        arguments:
            - { type: 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' }
        tags:
            - { name: 'miniblog.normalizer' }